source 'https://rubygems.org'

gem 'rails', '3.2.3'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'
gem 'haml-rails'

# Omniauth strategies
gem 'omniauth-weibo-oauth2'
gem 'omniauth-qq-connect'
gem 'omniauth-douban-oauth2'
gem 'omniauth-xiaonei'

gem 'simple_form'

# Password crypt
gem 'bcrypt-ruby', :require => 'bcrypt'

# Image process
gem 'mini_magick'
gem 'carrierwave-upyun'

gem 'remotipart', '~> 1.0'

gem 'acts_as_votable'

gem 'nokogiri'

gem 'ruby-pinyin'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'less-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  gem 'therubyracer', :platform => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
 gem 'unicorn'

group :development do
  gem 'capistrano'
  gem 'capistrano-unicorn', :require => false
end

group :production do
  gem 'mysql'
  gem 'mysql2'
end
# Deploy with Capistrano

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
